Add MySQL NodeJS-based Space Community Server
modelcontextprotocol/servers pull request #284
Opened 2024-12-09 18:53 UTC by benborla

Adding to the list of Community Servers - HuggingFace Space integration under an MIT License.

## Description
Added a new MCP server implementation `server-mysql` that enables querying MySQL databases through the Model Context Protocol. This server provides a secure and standardized way to interact with MySQL databases, supporting both single database queries and multi-database operations.

## Server Details
- Server: mysql
- Changes to: New server implementation

## Motivation and Context
This server implementation addresses the need for standardized database access through MCP, enabling LLMs to safely query MySQL databases while maintaining security and performance. Key features include:
- Configurable database connection management
- Support for single/multiple database querying
- Secure query execution with input validation
- Configurable access controls
- Comprehensive error handling
- Performance optimized connection pooling

## How Has This Been Tested?
Comprehensive testing has been performed including:
-  **Tests covered:**
   - [x] Connection management
   - [x] Query execution
   - [x] Error handling
   - [x] Input validation
   - [x] Access control
- **Security testing:**
   - [x] SQL injection prevention
   - [x] Access control validation
   - [x] Connection security

## Breaking Changes
None - This is a new server implementation that doesn't affect existing functionality.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist
- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My changes follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

## Additional context

### Documentation
- Added server-mysql to README.md
- Created detailed setup guide in /server-mysql/README.md including:
  - Installation instructions
  - Configuration options
  - Usage examples
  - Security best practices
  - Troubleshooting guide

### Configuration Example
claude_desktop_config.json
```json
{
  "mcpServers": {
    "mysql": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-mysql"
      ],
      "env": {
        "MYSQL_HOST": "127.0.0.1",
        "MYSQL_PORT": "33067",
        "MYSQL_USER": "root",
        "MYSQL_PASS": "",
        "MYSQL_DB": "db_name"
      }
    }
  }
}
```

2024-12-11 12:10 UTC, jspahrsummers requested changes
Thanks! Just some slight tweaks to the formatting/wording, then we'd be happy to get this in.

2024-12-11 12:10 UTC, jspahrsummers commented on README.md
> +- **[MySQL](https://github.com/benborla/mcp-server-mysql)** - (by benborla) MySQL database integration based on NodeJS with configurable access controls and schema inspection
```suggestion
- **[MySQL](https://github.com/designcomputer/mysql_mcp_server)** (by DesignComputer) - MySQL database integration in Python with configurable access controls and schema inspection
- **[MySQL](https://github.com/benborla/mcp-server-mysql)** (by benborla) - MySQL database integration in NodeJS with configurable access controls and schema inspection
```

2024-12-11 12:24 UTC, benborla commented
All good @jspahrsummers. Thank you for the tweak

2024-12-13 13:20 UTC, jspahrsummers approved these changes
Thank you!

2024-12-13 13:20 UTC, merged