Fixed GitHubFileContentSchema
modelcontextprotocol/servers pull request #316
Opened 2024-12-11 20:30 UTC by eybarta

There was a mismatch with the github response schema.. Reference from docs:
https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents 

```
"content": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "sha": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        },
        "url": {
          "type": "string"
        },
        "html_url": {
          "type": "string"
        },
        "git_url": {
          "type": "string"
        },
        "download_url": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "_links": {
          "type": "object",
          "properties": {
            "self": {
              "type": "string"
            },
            "git": {
              "type": "string"
            },
            "html": {
              "type": "string"
            }
          }
        }
      }
```

## Description
Bug fix in interface for github

## Server Details

- Server: 
- Changes to: 

## Motivation and Context

Bug fix:
https://github.com/modelcontextprotocol/servers/issues/165
## How Has This Been Tested?

No
## Breaking Changes

No
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [ x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [ x] My changes follows MCP security best practices
- [ ] I have updated the server's README accordingly
- [ ] I have tested this with an LLM client
- [ x] My code follows the repository's style guidelines
- [ ] New and existing tests pass locally
- [ ] I have added appropriate error handling
- [ ] I have documented all environment variables and configuration options

## Additional context

Just a minor mismatch in type.

2024-12-13 13:27 UTC, jspahrsummers requested changes
Thanks for submitting the fix! Just a couple of comments.

2024-12-13 13:27 UTC, jspahrsummers commented on src/github/schemas.ts
> -  content: z.string(),
This field is documented here: https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content

Can you please restore it?

2024-12-13 13:27 UTC, jspahrsummers commented on src/github/schemas.ts
> -  content: z.string(),
It could be made optional, though.

2024-12-13 13:27 UTC, jspahrsummers commented on src/github/schemas.ts
> +  html: z.string(),
These two should permit null values.

2025-02-07 01:22 UTC, jerome3o-anthropic commented
Looks like this was solved in https://github.com/modelcontextprotocol/servers/pull/434

Thanks for the PR none-the-less!

2025-02-07 01:22 UTC, closed without merging