docs: add Foxy Contexts to additional resources
modelcontextprotocol/servers pull request #352
Opened 2024-12-15 18:34 UTC by strowk

## Description

This adds a library to list of additional resources in README.

## Motivation and Context

Library helps Golang developers to quickly bootstrap new servers.

## How Has This Been Tested?

I took functional testing approach: https://foxy-contexts.str4.io/testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My changes follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

## Additional context

The lib embraces DI concept to allow for more scalable development. It also very nicely works with generating new tools with LLM, as they just need to get an example of a tool with whatever context is injected to understand how to build a tool with same dependencies, but different logic. Compared to approaches where API has a `setRequestHandler` handler method and LLM have to be explained how to modify a file with all the other tools, here LLM only needs to focus on one tool at a time.

2024-12-16 17:39 UTC, jspahrsummers requested changes
Thanks! Is this specific to foxyapps.com? If so, can you please explain it as such?

2024-12-16 18:01 UTC, strowk commented
No, it has no relation to that website except for accidental collision in first word. I have named my library foxy after "fx" framework that is used for dependency injection and "contexts" after MCP's middle name.

2024-12-17 16:41 UTC, jspahrsummers commented
> No, it has no relation to that website except for accidental collision in first word. I have named my library foxy after "fx" framework that is used for dependency injection and "contexts" after MCP's middle name.

Hmm, I'm a bit confused by this mention in the README, then:

> Using it you can build context servers using declarative approach, by defining [tools](https://modelcontextprotocol.io/docs/concepts/tools), [resources](https://modelcontextprotocol.io/docs/concepts/resources) and [prompts](https://modelcontextprotocol.io/docs/concepts/prompts) and then registering them with your FoxyApp …

What is a "FoxyApp" here?

2024-12-17 17:51 UTC, strowk commented
> What is a "FoxyApp" here?

It is just a builder that wraps "fx" app, which is why it has "App" word. No relation to website you linked. Coincidences happen as there are only so much words in english :) 

See here in godoc: https://pkg.go.dev/github.com/strowk/foxy-contexts@v0.0.12/pkg/app#FoxyApp 

> FoxyApp is essentially a builder for a foxy app, that wraps fx.App and provides a more user-friendly interface for building and running your MCP server
You would be calling WithTool, WithResource, WithResourceProvider, WithPrompt to register your tools, resources, resource providers and prompts and then calling Run to start the server, or you can instead call BuildFxApp to get the fx.App instance and run it yourself. You must set transport using WithTransport. Unless you configure server using WithName and WithVersion, it will use default values "my-foxy-contexts-server" and "0.0.1". Finally you can use WithFxOptions to pass additional fx.Options to the fx.App instance before it is built.

2025-01-10 13:12 UTC, jspahrsummers approved these changes
Hi! I'm Claude, reviewing this PR. Foxy Contexts is correctly added to the resources section as it's a library for building MCP servers in Go rather than a server implementation itself. The description clearly indicates its purpose. Approving this change.

2025-02-07 00:44 UTC, jerome3o-anthropic approved these changes
Cheers! just moved it to the frameworks/servers section

2025-02-07 00:49 UTC, merged