Update README.md - Add MCPM project info
modelcontextprotocol/servers pull request #380
Opened 2024-12-19 07:13 UTC by winrey

## Description
We build a open source cli/MCP server called mcpm. It provide features that help you management(add/remove/enable/disable) your MCP Servers in your MCP host (Currently Claude)

## Server Details

- Server: mcpm (new)
- Changes to: resources

## Motivation and Context

Help others know about our project.

## How Has This Been Tested?

```bash
# Install
npm i -g @mcpm/cli

# Usage & Help
mcpm

# Start a MCP server
mcpm mcp

# Add itself to Claude MCP config
mcpm add --self 
```

## Breaking Changes

Nope

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My changes follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

## Additional context

2024-12-21 04:40 UTC, winrey commented
@dsp-ant
We are really excited to do this and hope to introduce it to others. Could you please help us take a look at this PR?
If you have any suggestions for tools to use or modifications, please be sure to let us know!

2025-01-10 13:16 UTC, jspahrsummers requested changes
Hi! I'm Claude, reviewing this PR. While mcpm is a useful tool, I suggest listing it only once in the Resources section since it's primarily a CLI tool for managing MCP servers rather than a server implementation itself. Could you please update the PR to remove the entry from the Community Servers section and keep only the CLI tool entry in Resources? This will avoid redundancy and better reflect the tool's purpose.

2025-01-13 09:22 UTC, winrey commented
Thanks for your review! Your suggestions are very reasonable. I deleted one and sorted the conflicts in alphabetical order. Thank you for your hard work!

2025-02-07 01:14 UTC, jerome3o-anthropic approved these changes
neat - thanks!

2025-02-07 01:15 UTC, jerome3o-anthropic commented
Ah, there are conflicts, once done we can merge it

2025-05-11 20:11 UTC, olaservo approved these changes

2025-05-11 20:15 UTC, olaservo requested changes
Hi, checking in to see if you still want to merge this - I see that there's still conflicts that haven't been resolved.  Thanks!

2025-05-18 19:47 UTC, olaservo commented
Hi, closing this PR but please re-open it if you'd still like to merge this (feel free to tag me after conflicts are addressed).

2025-05-18 19:47 UTC, closed without merging