docs: add Redis, Travel Planner, JSON and Calendar MCP servers
modelcontextprotocol/servers pull request #413
Opened 2024-12-25 10:50 UTC by GongRzhe

## Description

Adding four new community MCP servers that expand the ecosystem's capabilities:

1. Redis MCP Server - For Redis database operations and caching
2. Travel Planner MCP Server - For travel planning using Google Maps API
3. JSON MCP Server - For JSON data processing and querying
4. Calendar MCP Server - For Google Calendar integration

## Server Details

Adding four new servers to the Community Servers section:

1. **Redis MCP Server**
   - Tools: set, get, delete, list
   - Features: Key-value operations, expiration management
   - Package: @gongrzhe/server-redis-mcp@1.0.0

2. **Travel Planner MCP Server**
   - Tools: searchPlaces, getPlaceDetails, calculateRoute, getTimeZone
   - Features: Location search, place details, route calculation
   - Package: @gongrzhe/server-travelplanner-mcp

3. **JSON MCP Server**
   - Tools: query, filter
   - Features: JSONPath operations, array/string/numeric/date operations
   - Package: @gongrzhe/server-json-mcp@1.0.3

4. **Calendar MCP Server**
   - Tools: create/update/delete/list events
   - Features: Google Calendar integration, OAuth2 authentication
   - Package: @gongrzhe/server-calendar-mcp

## Motivation and Context

These servers add important functionality to the MCP ecosystem:
- Database operations (Redis)
- Travel and location services (Travel Planner)
- Data processing and querying (JSON)
- Calendar management (Calendar)

## How Has This Been Tested?

All servers have been tested with Claude Desktop as the LLM client, with configuration examples provided in their respective READMEs.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation update

## Checklist

- [x] I have read the [MCP Protocol Documentation](https://modelcontextprotocol.io)
- [x] My changes follows MCP security best practices
- [x] I have updated the server's README accordingly
- [x] I have tested this with an LLM client
- [x] I have added appropriate error handling
- [x] I have documented all environment variables and configuration options

## Additional context

All servers are implemented in TypeScript/JavaScript and provide:
- Detailed installation instructions
- Configuration examples for Claude Desktop
- Clear documentation of tools and features
- Security considerations and best practices

2025-01-10 14:23 UTC, jspahrsummers requested changes
Hi! I'm Claude, and I'm reviewing this PR as part of the MCP project.

The README lists have been alphabetized. Could you please update the PR to add the Redis, Travel Planner, JSON and Calendar MCP server links in alphabetical order in the community servers section?

2025-01-13 03:27 UTC, GongRzhe commented
Thank you for the review! I've updated the PR and added the Gmail,  Redis, Travel Planner, JSON and Calendar MCP server links in alphabetical order in the community servers section as requested.

2025-01-13 03:27 UTC, GongRzhe commented
> Thank you for the review! I've updated the PR and added the Gmail, Redis, Travel Planner, JSON and Calendar MCP server links in alphabetical order in the community servers section as requested.



> Hi! I'm Claude, and I'm reviewing this PR as part of the MCP project.
> 
> The README lists have been alphabetized. Could you please update the PR to add the Redis, Travel Planner, JSON and Calendar MCP server links in alphabetical order in the community servers section?

Thank you for the review! I've updated the PR and added the Redis, Travel Planner, JSON and Calendar MCP server links in alphabetical order in the community servers section as requested.

2025-02-07 01:02 UTC, jerome3o-anthropic approved these changes
awesome - thanks, resolved a few conflicts and will merge now

2025-02-07 01:02 UTC, merged